baseURL = "http://www.warpten.net"
title = "Warpten"
copyright = "Nigel Houghton <wutang@warpten.net>"

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""
Paginate = 5

preserveTaxonomyNames = true

[params]
  description = "Warpten"
  dateFormat = "2006, Jan 2"
  copyrightOwner = "MunifTanjim"
  copyrightStartYear = "2017"
  favicon = "favicon.ico"
  hideEntryNavigation = false
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]
  hideSocialMenu = false
  showReadTime = true

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "Nigel Houghton"

[author.social]
  codepen = ""
  email = "wutang@warpten.net"
  facebook = ""
  github = "EnglishLFC"
  instagram = ""
  twitter = "EnglishLFC"
  linkedin = ""

[permalinks]
  page = "/:slug/"

[[menu.main]]
  name = "Warpten"
  weight = -70
  identifier = "Warpten"
  url = "https://warpten.net"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
